### ISSUE TITLE
Add option to introspect for timeout

### ISSUE THREAD

**Issue by Zzarek** [kaiserbergin/schema-smith#6]
Perhaps it would be worth while to add an option to introspect so that if this is happening there is an easy path to move ahead.

schemasmith introspect -t 120s or something.

`Unhandled exception: Neo4j.Driver.ClientException: The transaction has been terminated. Retry your operation in a new transaction, and you should see a successful result. The transaction has not completed within the specified timeout (dbms.transaction.timeout). You may want to retry with a longer timeout.
   at Neo4j.Driver.Internal.MessageHandling.ResponsePipelineError.EnsureThrownIf(Func`2 predicate)
   at Neo4j.Driver.Internal.MessageHandling.ResponsePipelineError.EnsureThrown()
   at Neo4j.Driver.Internal.Result.ResultCursorBuilder.NextRecordAsync()
   at Neo4j.Driver.Internal.Result.ResultCursor.FetchAsync()
   at Graphr.Neo4j.QueryExecution.QueryExecutor.<>c__DisplayClass10_0.<<ReadAsync>b__0>d.MoveNext()
`

**Comment by kaiserbergin** [comment]
That sounds like a possibility. The hard part is that the Driver will keep trying to connect even if you can't reach the endpoint (for example if you're in a VPN situation where you can't reach Aura or outside a VPN and can't reach a self-hosted instance in you VPN). 

Are you experiencing this issue due the above, or do you have an extremely large data set? You can always get an idea of the time by accessing your instance in Neo4j browser and running the following to get a feel for how long it should take to gage your timeout in the proposed change:

```
SHOW CONSTRAINTS;
SHOW INDEXES;
CALL apoc.meta.schema() yield value;
```

Let me know if the first suggestion is the root issue or if you need the additional argument. It should not be too difficult to get an update on the ask either way.

**Comment by Zzarek** [comment]
Unfortunately I don't have permissions to run that on the dataset, even in my dev .

 I'm also able to connect to the data via the driver via my application, as long as my timeout is extended. It has the same problem sometimes otherwise.
 
 So I'm confident this isn't the VPN

**Comment by kaiserbergin** [comment]
Sweet... Code changes made, but I'll need to test it out. I'll push a release tomorrow.
