### ISSUE TITLE
case matching prevents linter from accepting camelCase with number at the end

### ISSUE THREAD

**Issue by Zzarek** [kaiserbergin/schema-smith#7]
Imagine the common example - addressLine1

This leads to a warning in the linter, and the script won't generate due to the camel case not matching.  

`^[a-z][A-Z|a-z|/d]*\d*?$`  likely does the trick by just allowing numbers at the end. CamelCase is weird on numbers.

**Comment by kaiserbergin** [comment]
Thanks... I'll make the change and bundle it with tomorrow's release for the introspection request.

**Comment by kaiserbergin** [comment]
Fun fact, the issue is that I used forward instead of back slash on all my `d`'s. Facepalm. If I typed properly, it would have worked as intended. But you know... slash directions.

**Comment by Zzarek** [comment]
Awesome, Thanks for the speedy fix!
